package com.liveizy.propertyapi.dto.enums;

public enum Status {
    SUCCESS, CREATED, INTERNAL_ERROR, FAILED_VALIDATION, OLD_PASSWORD_INVALID, NOT_FOUND, NOT_PERMITTED, PAYMENT_REQUIRED, NO_RECORDS, PRECONDITION_FAILED

}
